name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git fetch
      run: git fetch
    - name: checkout www
      run: git checkout -t origin/www
    - name: ensure pull
      run: git pull
    - name: return to master
      run: git checkout master
    - name: Install dependencies
      run: lein deps
    - name: Build site
      run: ./build.sh
    - name: git reset www
      run: git reset www
    - name: delete non-dist folders
      run: ls | grep -v dist | xargs rm -r
    - name: pull contents out of dist
      run: cp -r dist/* .
    - name: delete dist folder
      run: rm -r dist
    - name: git add .
      run: git add .
    - name: git status
      run: git status
